url: https://Ollymid.github.io
baseurl: ""

# Site settings
title: Olly's Portfolio
email: ollymiddleton2@gmail.com
description: "My name is Olly and this is my online portfolio"


# Team names, titles and social links
people:
- name: Olly Middleton
  pic: 1
  position: Full Stack Web Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/Ollymid
  - title: stack-overflow
    url: http://stackoverflow.com/users/7841223/ollymid
  - title: github
    url: http://github.com/Ollymid

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:



# Build settings
markdown: kramdown
permalink: pretty
