url: https://Ollymid.github.io
baseurl: ""

# Site settings
title: Olly's Portfolio
description: "My name is Olly and this is my online portfolio"



# Build settings
markdown: kramdown
permalink: pretty
